***Data Transformation for Model Input (NumPy)<br>
Context: ML models require structured numeric arrays.***

**Create two arrays of shape (3,2)**

In [12]:
import numpy as np
data = [[3,4],
       [3,5],
       [7,1]]
numpy_array = np.array(data)
numpy_array.ndim

2

In [13]:
numpy_array.shape

(3, 2)

**Perform: Vertical stacking Horizontal stacking**

In [6]:
hstack = np.hstack(numpy_array)

array([3, 4, 3, 5, 7, 1])

In [7]:
np.vstack(numpy_array)

array([[3, 4],
       [3, 5],
       [7, 1]])

**Reshape into (2,6)**

In [15]:
reshape_array_2_6 = np.resize(numpy_array, (2,6))
reshape_array_2_6

array([[3, 4, 3, 5, 7, 1],
       [3, 4, 3, 5, 7, 1]])

In [16]:
reshape_array_2_6.shape

(2, 6)

**Explain: Why reshaping is required in ML pipelines**

Need to identify